### ISSUE TITLE
Missing `minsu3d.util.nms`

### ISSUE THREAD

**Issue by daveredrum** [3dlg-hcvc/minsu3d#16]
Hi team, I believe there's a file missing in [PointGroup](https://github.com/3dlg-hcvc/minsu3d/blob/main/minsu3d/model/pointgroup.py#L12), [HAIS](https://github.com/3dlg-hcvc/minsu3d/blob/main/minsu3d/model/hais.py#L12) and [SoftGroup](https://github.com/3dlg-hcvc/minsu3d/blob/main/minsu3d/model/softgroup.py#L11). Could you please add it?

**Comment by qiruiw** [comment]
Hi @daveredrum, thanks for trying out our repo!

The bug should be fixed with the recent commit. Please feel free to pull the latest code. Let us know if you have further questions~
