### ISSUE TITLE
[SoftGroup] How to get batched (pooled) instance features

### ISSUE THREAD

**Issue by MunzerDw** [3dlg-hcvc/minsu3d#21]
Hello,

In the SoftGroup forward pass, the instance level features are pooled into one vector per instance, which has a shape like (N, D) where N is the number of instances and D is 32. Since these feature vectors belong to different samples in one batch, how can I get which of the predicted instances belong to which batch sample? Essentially, I am looking to reshape them to (B, S, D), where B is batch_size and S is the number of instances in one sample.

I have looked into data["instance_offsets"] but I see that it has a different number of instances from the predicted ones, so I am not sure if I can use it.

Thank you for all your great work!

**Comment by eamonn-zh** [comment]
Sorry for the late reply. To separate instances features from different batches, you should first look at `data_dict["vert_batch_ids"]`, which tells you the batch number for each point, then `output_dict["proposals_idx"][:, 0]` tells the ids for predicted instances (note that ids themselves have no meaning, they are just used to distinguish different predicted instances), `output_dict["proposals_idx"][:, 1]` tells points belonging to those instances. Then you can get the (B, S, D) things you want. For detailed implementations, I recommend you to look at [https://github.com/daveredrum/D3Net/blob/b505e984cc4b01ea6ed95aa94b7bafa45215f4f4/model/pointgroup.py#L223](url), where they implemented exactly what you want, hope it helps. :smiley:
