### ISSUE TITLE
Error with scannet data preprocessing and pretrained model testing.

### ISSUE THREAD

**Issue by Maxcharm** [3dlg-hcvc/minsu3d#22]
After downloading the scannet dataset with commands in **data preparation code block 1**, I got two folders "scans" and "scan_test", then I try to preprocess the dataset with provided command in **data preparation code block 2**, but the generated "\*.pth" files in the "test" folder is incorrect because the test scenes are from "scan_test" folder instead of "scans" folder. I merge the two folders to get the correct "\*.pth" files.

However, after preprocessing, when I was trying to test pretrained pointgroup or softgroup models on the scannet dataset, it throws error **"ZeroDivisionError: division by zero"**. The problem is that in softgroup model's test step it calls function  
evaluate_semantic_accuracy(semantic_predictions, sem_labels_cpu.numpy(), ignore_label=self.hparams.data.ignore_label) and  prediction results are correnct but the ground truth labels are incorrect (all -1). Could you please help me with the problem?

To reproduce the error:
python test.py model=softgroup data=scannetv2 model.ckpt_path={pretrained_model_path}

**Comment by eamonn-zh** [comment]
Sorry for the late reply, please set the `inference.evaluate` flag to `False` in `config/model/base.yaml`  when you test models on the ScanNet test set since there is no ground truth due to ScanNet's setting.

**Comment by eamonn-zh** [comment]
Sorry for the late reply, we have fixed this issue, please pull the latest code from the main branch and try again. The issue is that ScanNet's hidden test set doesn't have GT, so you cannot evaluate them. The updated code automatically turns off the evaluation when you do an inference on the test set. Thank you for your feedback.
